### ISSUE TITLE
copynetWrapper cant wrap a attentionWrapper cell

### ISSUE THREAD

**Issue by bigsausage** [lspvic/CopyNet#3]
i read your Readme and see " Just wrapper an any existing rnn cell(`BasicLSTMCell`, `AttentionWrapper` and so on). " So i begin to try to wrap an AttentionWrapper In following ways:

first i use Attentionwrappper to wrap  a BasicLSTMCell and then i get a ,lets call it attention_cell
then i use the copynetWrapper to wrap the attention_cell and i got error :
''TypeError: The two structures don't have the same nested structure.""
in  CopyNetWrapperState's clone method.. 

when i get rid of attentionWrapper it works well...
i have no idea how to deal with this... 
hope anyone implement this can teach me ~thanks!

**Comment by lspvic** [comment]
```
cell = any_rnn_cell

copynet_cell = CopyNetWrapper(cell, encoder_outputs, encoder_input_ids,
    vocab_size, gen_vocab_size)
decoder_initial_state = copynet_cell.zero_state(batch_size,
    tf.float32).clone(cell_state=decoder_initial_state)
```

It seems that **decoder_initial_state** matters. The **decoder_initial_state** comes from the encoder's final state. If you wrap a BasicLSTMCell with Attentionwrappper, I think the *decoder_initial_state* should be
first converted to AttentionWrappperState,
RNN Cell: BasicLSTMCell -> AttentionWrapper -> CopyNetWrapper
RNN Cell State: encoder_final_state -> AttentionWrapperState -> CopyNetWrapperState

```
cell = AttentionWrapper(...)
decoder_initial_state = cell.zero_state(batch_size,
    tf.float32).clone(cell_state=decoder_initial_state)
# convert cell state to AttentionWrapperState.
copynet_cell = CopyNetWrapper(cell, encoder_outputs, encoder_input_ids,
    vocab_size, gen_vocab_size)
decoder_initial_state = copynet_cell.zero_state(batch_size,
    tf.float32).clone(cell_state=decoder_initial_state)
```

**Comment by lspvic** [comment]
But if you get rid of attentionWrapper it works well.
I wonder what the type of **decoder_initial_state**, if its type is not AttentionWrappperState, there should be some errors?

**Comment by bigsausage** [comment]
thanks so much!!!...
it is the decoder_initial_state problem.. 
i just dont know that i should convert the cell state to AttentionWrapperState first and then to CopyNetWrapper state.. 
i make the mistake by just convert the cell state to CopyNetWrapperState immediately..
really appreciate your solution!!!
thanks again!!!
